name: Push Docker Image

on:
  workflow_dispatch:
  
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set image tag
        id: tag
        run: echo "TAG=$(date +'%y.%m.%d')" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t '${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE }}:${{ env.TAG }}' -t '${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE }}:latest' .

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push '${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE }}:${{ env.TAG }}'
          docker push '${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE }}:latest'
