name: Deploy in VPS

on:
  workflow_dispatch:

  workflow_run:
    workflows: ["Push Docker Image"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
            docker rmi -f ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE }}:latest || true
            docker pull ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE }}:latest
            docker stop ${{ secrets.DOCKER_CONTAINER}} || true
            docker rm ${{ secrets.DOCKER_CONTAINER}} || true
            docker run -d --name '${{ secrets.DOCKER_CONTAINER}}' \
              -e 'DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}' \
              -e 'HOSTS=${{ secrets.HOSTS }}' \
              -e 'PG_DB=${{ secrets.PG_DB }}' \
              -e 'PG_USER=${{ secrets.PG_USER }}' \
              -e 'PG_PASS=${{ secrets.PG_PASS }}' \
              -e 'PG_HOST=${{ secrets.PG_HOST }}' \
              -e 'PG_PORT=${{ secrets.PG_PORT }}' \
              -p '${{ secrets.DOCKER_HOST_PORT }}:8000' \
              --network '${{ secrets.DOCKER_NETWORK }}' \
              '${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE }}:latest'
